import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>title</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <header>this is header</header>
        <h1>main</h1>
        <p>良い感じのコンテンツ</p>
      </main>

      <footer>
        <p>footter</p>
      </footer>
    </div>
  );
}
